# Generated by Django 2.1.7 on 2019-03-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190326_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationdata',
            old_name='pd',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='registrationdata',
            old_name='user',
            new_name='username',
        ),
    ]
