# Generated by Django 2.1.7 on 2019-04-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_booking_pay_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='checkout_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pay_status',
        ),
    ]
