# Generated by Django 2.1.7 on 2019-04-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20190407_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='city',
            field=models.CharField(choices=[('Mangalore', 'Mangalore'), ('Surathkal', 'Surathkal'), ('Udupi', 'Udupi'), ('Manipal', 'Manipal')], default='Surathkal', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_no',
            field=models.CharField(default='+91 ', max_length=14),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_size',
            field=models.CharField(choices=[('Personal vehicle', 'Personal vehicle'), ('Commercial vehicle', 'Commercial vehicle'), ('Sport utility vehicle', 'Sport utility vehicle'), ('Special purpose vehicle', 'Special purpose vehicle')], default='Personal vehicle', max_length=30),
        ),
    ]
