# Generated by Django 2.1.7 on 2019-04-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190401_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_no',
            field=models.CharField(default='+91 ', max_length=10),
        ),
    ]
