# Generated by Django 2.1.7 on 2019-04-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_booking_vehicle_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='driver_license',
            field=models.CharField(max_length=30),
        ),
    ]
