# Generated by Django 2.1.7 on 2019-04-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190405_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='city',
            field=models.CharField(choices=[('Mangalore', 'Mangalore'), ('Surathkal', 'Surathkal'), ('Udupi', 'Udupi'), ('Manipal', 'Manipal')], default='Surathkal', max_length=1),
        ),
    ]
