# Generated by Django 2.1.7 on 2019-04-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_booking_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
