# Generated by Django 2.1.7 on 2019-04-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20190406_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pay_status',
            field=models.BooleanField(default=False),
        ),
    ]
