# Generated by Django 2.1.7 on 2019-04-07 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190407_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='driver_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
