# Generated by Django 2.1.7 on 2019-04-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190407_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='driver_name',
            field=models.CharField(max_length=30),
        ),
    ]
