# Generated by Django 2.1.7 on 2019-10-11 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20190408_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkout_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
