# Generated by Django 2.1.7 on 2019-10-12 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20191012_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='block',
            field=models.CharField(choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='5', max_length=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='floor',
            field=models.CharField(choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='5', max_length=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='space',
            field=models.CharField(choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='5', max_length=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 17, 23, 24, 190881)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 17, 23, 24, 190881)),
        ),
    ]
