# Generated by Django 2.1.7 on 2019-10-12 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20191012_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=16)),
                ('card_hold_name', models.CharField(max_length=30)),
                ('card_exp_date', models.CharField(max_length=5)),
                ('card_cvv', models.CharField(max_length=3)),
                ('postal_code', models.CharField(max_length=6)),
                ('user_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 17, 54, 25, 513434)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 17, 54, 25, 513434)),
        ),
    ]
