# Generated by Django 2.1.7 on 2019-10-12 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20191012_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 13, 0, 16, 12, 389366)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 13, 0, 16, 12, 389366)),
        ),
        migrations.AlterField(
            model_name='paycards',
            name='card_cvv',
            field=models.CharField(default='002', max_length=3),
        ),
        migrations.AlterField(
            model_name='paycards',
            name='card_exp_date',
            field=models.CharField(default='01/01', max_length=5),
        ),
        migrations.AlterField(
            model_name='paycards',
            name='card_hold_name',
            field=models.CharField(default='TestUser', max_length=30),
        ),
        migrations.AlterField(
            model_name='paycards',
            name='postal_code',
            field=models.CharField(default='673604', max_length=6),
        ),
    ]
