# Generated by Django 2.1.7 on 2019-10-12 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20191013_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 13, 1, 6, 31, 681294)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 13, 1, 6, 31, 681294)),
        ),
    ]
