# Generated by Django 2.1.7 on 2019-10-13 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20191013_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paycards',
            name='id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 13, 9, 8, 20, 245055)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 13, 9, 8, 20, 246053)),
        ),
        migrations.AlterField(
            model_name='paycards',
            name='card_no',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
