# Generated by Django 2.1.7 on 2019-10-13 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20191013_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 13, 9, 17, 30, 792813)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 13, 9, 17, 30, 792813)),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('driver_license', 'active_status')},
        ),
    ]
