# Generated by Django 2.1.7 on 2019-10-15 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20191013_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 0, 48, 14, 390055)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 0, 48, 14, 390055)),
        ),
    ]
