# Generated by Django 2.1.7 on 2019-04-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
